config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'ranking', to: 'posts#ranking'
  get 'ranking/cake', to:'posts#cake'
  get 'ranking/ice', to:'posts#ice'
  get 'ranking/cookie', to:'posts#cookie'
  get 'ranking/others', to:'posts#others'
  

  resources :users, only: [:index, :show, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :posts, only: [:create, :destroy, :show] 
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50}
    validates :email, presence: true, length: { maximum: 50}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
    validates :introduction, presence: false, length: { maximum: 100 }
    validates :avater, presence: false
    mount_uploader :avater, AvaterUploader
    has_secure_password
    
    has_many :posts
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
    has_many :followers, through: :reverses_of_relationship, source: :user
    
    def follow(other_user)
        unless self == other_user
          self.relationships.find_or_create_by(follow_id: other_user.id)
        end
    end

    def unfollow(other_user)
        relationship = self.relationships.find_by(follow_id: other_user.id)
        relationship.destroy if relationship
    end

    def following?(other_user)
        self.followings.include?(other_user)
    end
    
    has_many :favorites
    has_many :favorited_posts, through: :favorites, source: :post
    
    def favorite(post)
        self.favorites.find_or_create_by(post_id: post.id)
    end
    
    def unfavorite(post)
        favorite = self.favorites.find_by(post_id: post.id)
        favorite.destroy if favorite
    end
    
    def favorite?(post)
        self.favorited_posts.include?(post)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers]
  
  def index
    @pagy, @users = pagy(User.order(id: :desc), items: 9)
  end

  def show
    @user = User.find(params[:id])
    @pagy, @posts = pagy(@user.posts.order(id: :desc), items: 9)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_edit_params)
        flash[:success] = "Profileは正常にUpdateされました"
        redirect_to users_url
    else
        flash.now[:danger] = "ProfileはUpdateされませんでした"
        render :edit
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @pagy, @followings = pagy(@user.followings)
    counts(@user)
  end

  def followers
    @user = User.find(params[:id])
    @pagy, @followers = pagy(@user.followers)
    counts(@user)
  end
  
  def likes
    #loginしているuserのidを取得
    @user = User.find(params[:id])
    #そのuserがフォローしている人たちを取得して、一覧表示
    @pagy,@likes = pagy(@user.favorited_posts.order(created_at: :desc))
    #フォローしている人たちの人数をカウント
    counts(@user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def user_edit_params
    params.require(:user).permit(:avater, :introduction)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_edit_button.html.erb
<%if current_user == @user %>
  <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-outline-secondary btn-sm' %>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <div class="row">
    <% users.each do |user| %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card-user shadow bg-white rounded">
          <% if user.avater.present? %>
              <%= image_tag user.avater.url, size: "350x350" %>
            <% else %>
              <%= image_tag "/sample.jpeg", size: "350x350" %>
            <% end %>
          <div class="card-body">
            <div class="text-center">
              <h3><%= user.name %></h3>
            </div>
            <div class="row justify-content-end">
              <div class="col-auto">
                <%= link_to 'View profile', user_url(user), class: 'btn btn-secondary btn-sm' %>
              </div>
              <div class="col-3 offset-1">
                <%= render 'relationships/follow_button', user: user %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="m-5">
  <%== pagy_bootstrap_nav(@pagy) %>
  </div>
<% end %>

app/views/users/edit.html.erb
  <div class="py-5 bg-light">
    <%= form_with(model: @user) do |f| %>
      <div class="row align-items-center justify-content-around">
        <div class="col-md-6">
          <div class="img-upload m-5">
            <div id="image-list"></div>
            <div class="clik-upload">
            <%= f.file_field :avater, id:"post_img" %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="m-5">
            <%= f.label :introduction, 'Introduction' %>
            <div class="d-flex align-items-center justify-content-center">
              <%= f.text_area :introduction, class: 'form-control', rows: 7 %>
            </div>
          </div>
        </div>
      </div>
      <div class="text-center"> 
        <%= f.submit 'Update', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

app/views/users/followers.html.erb
<div class="m-3 text-center">
  <% if @user.avater.present? %>
    <div>
      <%= image_tag @user.avater.url, size: "350x350" %>
    </div>
    <% else %>
      <%= image_tag "sample.jpeg", id: :img_prev %>
    <% end %>
</div>
<div class="text-center">
    <h3><%= @user.name %></h3>
</div>
<div class=row>
  <div class="offset-7 col-3">
      <%= render 'relationships/follow_button', user: @user %>
      <%= render 'edit_button', user: @user %>
  </div>
</div>
</div>
<div class="text-center mb-5">
  <p><%= @user.introduction %></p>
</div>
<div class=mx-5>
  <ul class="nav nav-tabs nav-justified mb-3">
  <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Photo  <span class="badge bg-secondary"><%= @count_posts %></span></a></li>
  <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge bg-secondary"><%= @count_followings %></span></a></li>
  <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge bg-secondary"><%= @count_followers %></span></a></li>
  <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Favorites  <span class="badge bg-secondary"><%= @count_favorites %></span></a></li>
  </ul>
  <%= render 'users', users: @followers %>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Photos  <span class="badge bg-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge bg-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge bg-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<div class="texts-wrapper">
  <div class="contents-title text-center m-5">
    <h1>ユーザー一覧</h1>
  </div>
    <%= render 'users', users: @users %>
</div>

app/views/users/likes.html.erb
<div class="m-3 text-center">
  <% if @user.avater.present? %>
    <div>
      <%= image_tag @user.avater.url, size: "350x350" %>
    </div>
    <% else %>
      <%= image_tag "sample.jpeg", id: :img_prev %>
    <% end %>
</div>
<div class="text-center">
    <h3><%= @user.name %></h3>
</div>
<div class=row>
  <div class="offset-7 col-3">
      <%= render 'relationships/follow_button', user: @user %>
      <%= render 'edit_button', user: @user %>
  </div>
</div>
</div>
<div class="text-center mb-5">
  <p><%= @user.introduction %></p>
</div>
<div class=mx-5>
  <ul class="nav nav-tabs nav-justified mb-3">
  <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Photo  <span class="badge bg-secondary"><%= @count_posts %></span></a></li>
  <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge bg-secondary"><%= @count_followings %></span></a></li>
  <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge bg-secondary"><%= @count_followers %></span></a></li>
  <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Favorites  <span class="badge bg-secondary"><%= @count_favorites %></span></a></li>
  </ul>
  <%= render 'posts/posts', posts: @likes %>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
    
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents-title text-center m-5">
      <h1>Profile</h1>
</div>
<div class="m-3 text-center">
  <% if @user.avater.present? %>
    <div>
      <%= image_tag @user.avater.url, size: "350x350" %>
    </div>
    <% else %>
      <%= image_tag "/sample.jpeg", size: "350x350" %>
    <% end %>
</div>
<div class="text-center">
    <h3><%= @user.name %></h3>
</div>
<div class="text-center mb-3">
  <p><%= @user.introduction %></p>
</div>
<div class="row mb-5">
  <div class="offset-7 col-3">
      <%= render 'relationships/follow_button', user: @user %>
      <%= render 'edit_button', user: @user %>
  </div>
</div>
</div>
<div class=mx-5>
  <ul class="nav nav-tabs nav-justified mb-3">
  <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Photo  <span class="badge bg-secondary"><%= @count_posts %></span></a></li>
  <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge bg-secondary"><%= @count_followings %></span></a></li>
  <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge bg-secondary"><%= @count_followers %></span></a></li>
  <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Favorites  <span class="badge bg-secondary"><%= @count_favorites %></span></a></li>
  </ul>
  <%= render 'posts/posts', posts: @posts %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>