config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'ranking', to: 'posts#ranking'
  get 'ranking/cake', to:'posts#cake'
  get 'ranking/ice', to:'posts#ice'
  get 'ranking/cookie', to:'posts#cookie'
  get 'ranking/others', to:'posts#others'
  

  resources :users, only: [:index, :show, :create, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
    end
  end
  
  resources :posts, only: [:create, :destroy, :show] 
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :img, presence: true
  validates :genre, presence: true, length: { maximum: 50 }
  validates :location, presence: true, length: { maximum: 50 }
  validates :text, presence: false, length: { maximum: 100 }
  mount_uploader :img, ImgUploader
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿しました。'
      redirect_to root_url
    else
      @pagy, @posts = pagy(current_user.posts.order(id: :desc), items: 9)
      flash.now[:danger] = '投稿に失敗しました。'
      render 'toppages/index'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_to root_url
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def ranking
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end
  
  def cake
    @cake_ranks = Post.joins(:favorites).group('posts.id').where(genre: 'cake').order('count(post_id) desc').limit(3)
  end
  
  def cookie
    @cookie_ranks = Post.joins(:favorites).group('posts.id').where(genre: 'cookie').order('count(post_id) desc').limit(3)
  end
  
  def ice
    @ice_ranks = Post.joins(:favorites).group('posts.id').where(genre: 'ice').order('count(post_id) desc').limit(3)
  end
  
  def others
    @others_ranks = Post.joins(:favorites).group('posts.id').where(genre: 'others').order('count(post_id) desc').limit(3)
  end
  
  private
  
  def post_params
    params.require(:post).permit(:img, :genre, :location, :text)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/_image.html.erb
<% if posts.any? %>
  <ul class="list-unstyled mt-2">
    <% posts.each do |post| %>
      <li class="d-flex">
        <img class="rounded me-2 mb-5" src="<%= gravatar_url(post.user, { size: 64 }) %>" alt="">
        <div>
          <div>
            <%= link_to post.user.name, user_path(post.user), class: "text-decoration-none" %> <span class="text-muted">posted at <%= post.created_at %></span>
          </div>
          <div>
            <p><%= post.content %></p>
          </div>
          <table>
            <td>
            <%if current_user == post.user %>
              <%= link_to 'Delete', post, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
            <% end %>
            </td>
            <td>
              <%= render 'favorites/favorite_button', post: post %>
            </td>
          </table>
        </div>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/posts/_posts.html.erb
<% if posts.any? %>
<div class="row">
    <% posts.each do |post| %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card-post shadow bg-white rounded">
          <%= image_tag post.img.url, size: "350x350" %>
          <div class="card-body">
            <div class="d-flex align-items-center">
              <div class="p-1 flex-grow-1">
                <h3><%= link_to post.user.name, user_path(post.user), class: "text-decoration-none" %></h3>
              </div>
              <div class="p-1">
                <%= link_to 'View', post, class: "btn btn-outline-secondary btn-sm" %>
              </div>
              <div class="p-1">
                <%= render 'favorites/favorite_button', post: post %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>
<div class="pagination">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>
<% end %>

app/views/posts/_ranking.html.erb
<% posts.each.with_index(1) do |post, i| %>
  <div class="mt-5 mb-2 ranking">
    <i class="far fa-star"></i>
    <p><%= i %></p>
  </div>
  <div class="py-5 bg-light">
    <div class="row">
      <div class="col-md-6">
        <div class="m-5">
            <div>
              <%= image_tag post.img.url, size: "350x350" %>
              <div class="text-center m-3">
                <h1><%= link_to post.user.name, user_path(post.user), class: "text-decoration-none" %></h1>
              </div>
            </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="m-5">
          <h4>Genre</h4>
          <p class="m-2"><%= post.genre %></p>
        </div>
        <div class="m-5">
          <h4>Location</h4>
          <p class="m-2"><%= post.location %></p>
        </div>
        <div class="m-5">
          <h4>Text</h4>
          <p class="m-2"><%= post.text %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/cake.html.erb
<div class="texts-wrapper">
  <div class="contents-title text-center m-5">
    <h1>いいねランキング</h1>
  </div>
  <div class=mx-5>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= ranking_path %>" class="nav-link">All</a></li>
      <li class="nav-item"><a href="<%= ranking_cake_path %>" class="nav-link">Cake</a></li>
      <li class="nav-item"><a href="<%= ranking_cookie_path %>" class="nav-link">Cookie</a></li>
      <li class="nav-item"><a href="<%= ranking_ice_path %>" class="nav-link">Ice</a></li>
      <li class="nav-item"><a href="<%= ranking_others_path %>" class="nav-link">Others</a></li>
    </ul>
    <div class="contents-title text-center m-5">
      <h2>Cake</h2>
    </div>
    <%= render 'ranking', posts: @cake_ranks %>
  </div>
</div>

app/views/posts/cookie.html.erb
<div class="texts-wrapper">
  <div class="contents-title text-center m-5">
    <h1>いいねランキング</h1>
  </div>
  <div class=mx-5>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= ranking_path %>" class="nav-link">All</a></li>
      <li class="nav-item"><a href="<%= ranking_cake_path %>" class="nav-link">Cake</a></li>
      <li class="nav-item"><a href="<%= ranking_cookie_path %>" class="nav-link">Cookie</a></li>
      <li class="nav-item"><a href="<%= ranking_ice_path %>" class="nav-link">Ice</a></li>
      <li class="nav-item"><a href="<%= ranking_others_path %>" class="nav-link">Others</a></li>
    </ul>
    <div class="contents-title text-center m-5">
      <h2>Cookie</h2>
    </div>
    <%= render 'ranking', posts: @cookie_ranks %>
  </div>
</div>

app/views/posts/ice.html.erb
<div class="texts-wrapper">
  <div class="contents-title text-center m-5">
    <h1>いいねランキング</h1>
  </div>
  <div class=mx-5>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= ranking_path %>" class="nav-link">All</a></li>
      <li class="nav-item"><a href="<%= ranking_cake_path %>" class="nav-link">Cake</a></li>
      <li class="nav-item"><a href="<%= ranking_cookie_path %>" class="nav-link">Cookie</a></li>
      <li class="nav-item"><a href="<%= ranking_ice_path %>" class="nav-link">Ice</a></li>
      <li class="nav-item"><a href="<%= ranking_others_path %>" class="nav-link">Others</a></li>
    </ul>
    <div class="contents-title text-center m-5">
      <h2>Ice</h2>
    </div>
    <%= render 'ranking', posts: @ice_ranks %>
  </div>
</div>

app/views/posts/others.html.erb
<div class="texts-wrapper">
  <div class="contents-title text-center m-5">
  <h1>いいねランキング</h1>
  </div>
  <div class=mx-5>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= ranking_path %>" class="nav-link">All</a></li>
      <li class="nav-item"><a href="<%= ranking_cake_path %>" class="nav-link">Cake</a></li>
      <li class="nav-item"><a href="<%= ranking_cookie_path %>" class="nav-link">Cookie</a></li>
      <li class="nav-item"><a href="<%= ranking_ice_path %>" class="nav-link">Ice</a></li>
      <li class="nav-item"><a href="<%= ranking_others_path %>" class="nav-link">Others</a></li>
    </ul>
    <div class="contents-title text-center m-5">
      <h2>Others</h2>
    </div>
    <%= render 'ranking', posts: @others_ranks %>
  </div>
</div>

app/views/posts/ranking.html.erb
<div class="texts-wrapper">
  <div class="contents-title text-center m-5">
    <h1>いいねランキング</h1>
  </div>
  <div class=mx-5>
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= ranking_path %>" class="nav-link">All</a></li>
      <li class="nav-item"><a href="<%= ranking_cake_path %>" class="nav-link">Cake</a></li>
      <li class="nav-item"><a href="<%= ranking_cookie_path %>" class="nav-link">Cookie</a></li>
      <li class="nav-item"><a href="<%= ranking_ice_path %>" class="nav-link">Ice</a></li>
      <li class="nav-item"><a href="<%= ranking_others_path %>" class="nav-link">Others</a></li>
    </ul>
    <div class="contents-title text-center m-5">
      <h2>All</h2>
    </div>
    <%= render 'ranking', posts: @all_ranks %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="texts-wrapper">
  <div class="contents-title text-center m-3">
    <h1>投稿詳細</h1>
  </div>
</div>
<div class="py-5 bg-light">
  <div class="row">
    <div class="col-md-6">
      <div class="m-5">
          <div class="text-center">
            <%= image_tag @post.img.url, size: "350x350" %>
            <div class="text-center m-3">
              <h1><%= link_to @post.user.name, user_path(@post.user), class: "text-decoration-none" %></h1>
            </div>
          </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="m-5">
        <h4>Genre</h4>
        <p class="m-2"><%= @post.genre %></p>
      </div>
      <div class="m-5">
        <h4>Location</h4>
        <p class="m-2"><%= @post.location %></p>
      </div>
      <div class="m-5">
        <h4>Text</h4>
        <p class="m-2"><%= @post.text %></p>
      </div>
    </div>
    <div class="text-center">
        <%if current_user == @post.user %>
          <%= link_to 'Delete', @post, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger'%>
        <% end %>
      </div>
  </div>
</div>